---
# tasks file for nfd
- name: add ndn user
  user: name=ndn state=present shell=/bin/false createhome=no

#- name: add ndnsec user
#  user: name=ndnsec state=present shell=/bin/bash password=LrVkOUM1s16xE

- name: make ndn required directories
  file: path=/etc/ndn state=directory owner=ndn group=ndn mode=0755
- file: path=/etc/ndn/keys state=directory owner=ndn group=ndn mode=0755
- file: path=/var/lib/ndn state=directory owner=ndn group=ndn mode=0755
- file: path=/var/log/ndn state=directory owner=ndn group=ndn mode=0755

#- cron: name="log rotate" user="ndnops" hour="1" minute="1" job="/home/ndnops/ndn-ops/NOC/logRotation/rotateLogs.sh  "
- cron: name="log rotate" user="ndnops" minute="28" job="/home/ndnops/ndn-ops/NOC/bin/rotateLogs.sh  "

- name: install nfd
  apt: name=nfd state=latest update_cache=yes

- name: install nfd-dbg
  apt: name=nfd-dbg state=latest update_cache=yes

- name: copy root key
  #copy: dest=/etc/ndn/keys/ansible_ndn-testbed-root.ndncert.base64 src=roles/nfd/files/ndn-testbed-root.ndncert.base64 owner=root group=root mode=0644
  copy: dest=/etc/ndn/keys/ndn-testbed-root.ndncert.base64 src=roles/nfd/files/ndn-testbed-root.ndncert.base64 owner=root group=root mode=0644

- name: copy openmhealth key
  copy: dest=/etc/ndn/keys/openmhealth.cert src=roles/nfd/files/openmhealth.cert owner=root group=root mode=0644

- name: create nfd-init.sh
  #template: src=nfd-init.sh.j2 dest=/etc/ndn/ansible_nfd-init.sh  owner=root group=root mode="u=rwx,g=rx,o=rx"
  template: src=nfd-init.sh.j2 dest=/etc/ndn/nfd-init.sh  owner=root group=root mode="u=rwx,g=rx,o=rx"
  notify: restart nfd

- name: create nfd.conf
  #template: src=nfd.conf.j2 dest=/etc/ndn/ansible_nfd.conf owner=root group=root mode="u=rw,g=r,o=r"
  template: src=nfd.conf.j2 dest=/etc/ndn/nfd.conf owner=root group=root mode="u=rw,g=r,o=r"
  notify: restart nfd

- name: start nfd
  service: name=nfd state=started enabled=yes

# The problem is that we want to restart nfd sometimes before something like NLSR restarts
# and sometimes after NLSR restarts...
# restart nfd immediately, don't wait for end of playbook
#- meta: flush_handlers

